### ISSUE TITLE
document execution 

### ISSUE THREAD

**Issue by alvamich** [Tekunalogy/Redshelf_Textbook_Scraper#1]
appreciate a minimum how to for running the program. tx.

**Comment by Tekunalogy** [comment]
People have told me it no longer works with the updates to redshelf. Although I have no way to test, I don't have access to redshelf free trial.

But essentially, you have to go into chrome inspect element, and go into sources and looks for the IDs for the book pages and stuff. Then I use selenium to increment those IDs or smth. I wrote this a while back, so this isn't really a top priority for me since it was one and done. I will probably archive this repo.
